ga_config:
  # Number of days to analyze
  default_days: 30

  # Maximum number of rows to fetch
  row_limit: 10000

  # GA4 metrics to analyze
  metrics:
    - totalUsers
    - newUsers
    - activeUsers
    - sessions
    - averageSessionDuration
    - screenPageViews
    - eventCount
    - engagementRate

  # GA4 dimensions to analyze
  dimensions:
    - date
    - deviceCategory
    - country
    - pagePath
    - sessionDefaultChannelGroup
    - firstUserSource
    - firstUserMedium
